# Base Environment
FROM node:16.0.0-alpine
# Set the working directory
WORKDIR /app
# Copy package files
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy all other source code files
COPY . .
# ENV variables
ENV NODE_ENV development
ENV DB_NAME twitter_clone_dev
ENV DB_HOST host.docker.internal
ENV DB_PORT 3306
ENV DB_USER root
ENV DB_PASSWORD 12345
ENV PORT 8080
ENV SECRET_KEY 123456
ENV MAILGUN_API_KEY=YOUR_MAILGUN_API_KEY

# Expose port 
EXPOSE 8080
# Command to start the application
CMD ["npm", "run", "start"]
#CMD ["node", "index.js"]
